### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by guilbep** [EPFL-ENAC/epfl-enac-build-push-deploy-action#1]
- [x] add proper documentation on how to use and versions
- [x] Centralize version for all CD_TOKEN (one to rule them all)
- [ ] Have error handling for CURL (401 should return an exit 1 and have pipeline failed)
- [ ] Bonuse have trigger dispatch event check the status of the workflow running on eenack8s-app-config
- [ ] Use action.yml default to use local workflow via the following if possible
```
using: "composite"
  steps:
    - name: Call reusable workflow
      run: |
        gh workflow run .github/workflows/deploy-prod.yml --ref ${{ github.ref }}
```

**Comment by guilbep** [comment]
Status check on the remaining boxes, 2026-09-18: the curl error handling exists (`curl --fail` on the dispatch in update-manifest, a 401 fails the job). The dispatch status check and the composite-action wrapper are still open; the action now runs the chart publish, the registry copies and image reuse inside the reusable workflow (3.3.0 to 3.6.0), so the composite idea would only wrap a `gh workflow run`.
